//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArbitratorTrackFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class arbitrator_assignment
    {
        public int id { get; set; }
        public string req_id { get; set; }
        public string mediserv_filer { get; set; }
        public string arbitrator { get; set; }
        public string judge { get; set; }
        public int no_of_claims { get; set; }
        public System.DateTime date_assigned { get; set; }
        public decimal total_fee { get; set; }
        public string request_for_payment { get; set; }
        public decimal our_fee { get; set; }
        public string health_plan { get; set; }
        public decimal hp_original_payment { get; set; }
        public decimal hp_final { get; set; }
        public decimal th_final { get; set; }
        public System.DateTime packet_due_date { get; set; }
        public System.DateTime packet_sent_to_arbitrator { get; set; }
        public Nullable<decimal> final_offer { get; set; }
        public string note { get; set; }
        public bool copy_of_packet_to_health_plan { get; set; }
        public Nullable<bool> did_we_receive_hp_packet { get; set; }
        public string outcome { get; set; }
        public Nullable<decimal> reasonable_fee { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string arbitrators_percent_of_medicare { get; set; }
        public string cpt { get; set; }
        public int eligible_green_id { get; set; }
    
        public virtual eligible_green eligible_green { get; set; }
    }
}
