//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArbitratorTrackFlow.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArbitrationTrackFlowEntities : DbContext
    {
        public ArbitrationTrackFlowEntities()
            : base("name=ArbitrationTrackFlowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<arbitrator_assignment> arbitrator_assignment { get; set; }
        public virtual DbSet<clinical_summaries> clinical_summaries { get; set; }
        public virtual DbSet<eligible_green> eligible_green { get; set; }
        public virtual DbSet<eligible_yellow_blue> eligible_yellow_blue { get; set; }
    }
}
