//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArbitratorTrackFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eligible_yellow_blue
    {
        public int id { get; set; }
        public Nullable<bool> ineligible { get; set; }
        public string reason { get; set; }
        public string req_id { get; set; }
        public Nullable<System.DateTime> date_filed { get; set; }
        public string filer { get; set; }
        public bool strikethrough { get; set; }
        public int eligible_green_id { get; set; }
    
        public virtual eligible_green eligible_green { get; set; }
    }
}
